### ISSUE TITLE
tier push does not prevent new features from being pushed to existing plans

### ISSUE THREAD

**Issue by jevon** [tierrun/tier#120]
### What is the issue?

If I already have a published plan and I edit my pricing.json, I may forget to update the plan version before I push. 

If all I have done is to add a feature to a plan, then that feature will be pushed under the not-edited plan version. 

This could be useful functionality in a price grandfathering scenario: I may want to retroactively add a newly create feature to an old plan in order to grant the subscribers of the old plan (at an old price) access to the new feature. That should be an exception however.

I believe we should error on a push in this scenario. *If* we want to allow it was a way to grandfather, then that should be explicit? That would depend on how we want to handle grandfathering. 

The behaviour exists whether or not there is a subscriber to the plan. It may make sense to allow this behaviour if there are no subscribers on the plan.

### Steps to reproduce

1. Create a pricing.json:

`{
    "plans": {
      "plan:pro@13": {
        "title": "Trip Pro Plan",
        "features": {
          "feature:flights": {
             "base": 1000
          }
        }
      }
    }
  }`

2. tier push this plan

3. tier pull to check that it is there

4. Now edit the pricing.json to add a new feature, but do not update the plan version:

`{
    "plans": {
      "plan:pro@13": {
        "title": "Trip Pro Plan",
        "features": {
          "feature:flights": {
             "base": 1000
          }
        },
        "feature:activities": {
          "tiers": [ 
            { "price": 1 } 
          ]
        }
      }
    }
  }`

5. tier push the updated pricing.json
6. **tier pull** *or* Log in to Stripe dashboard and observe the new feature is present and live under the previous @version of the plan

### Tier version

0.3.7

**Comment by bmizerany** [comment]
The correct behavior should be to abort any pricing.json update on `push` by default. However, this can be cumbersome in test mode when one wants to get a feel for new plans and features they are working on. In this case, we can allow a "force push".

I'm moving this to "In Progress".

**Comment by shripadk** [comment]
@bmizerany Really like the idea of force push for testing as well as for grandfathered plans. Will it also takes into account updating tier price and feature settings (like mode/aggregate) when force-pushed? Adding a new feature to existing plan works as of now (as shown by @jevon). However, existing tier price and feature settings changes are currently not updated. So have to manually delete the plans and re-push them for now in test mode.

**Comment by bmizerany** [comment]
@shripadk I'm wondering if we need a force push now that `tier switch` is released, which is helpful in the case where one has done enough "damage" they want to start over. When it is a minor update, changing the plan version is a quick way to update a plan. 

NOTE: If force-push is implemented, it will not affect customers already on the plan; they would instead be seen to tier as having "fragments" and would not be considered on any plan (assuming they were not subscribed to two plans at once), and this should not be allowed by Tier in live-mode, so it could be cause confusion amongst users as to why behaviors around subscriptions and limits, etc suddenly changed for customers that have not upgraded or downgraded in a way one might think they should be.

I'm not sure we need force-push now, but I'm not 100% sold on that. Have your thoughts changed now that `tier switch` is out?

https://www.tier.run/docs/cli/switch

**Comment by shripadk** [comment]
@bmizerany I saw the `tier switch` tweet on Twitter few hours back. Really excited to read about the changes (been up all night working, so heading to bed now). Will check once I wake up. I'll get back to your questions as soon as I give `tier switch` a try. Thank you!

**Comment by shripadk** [comment]
@bmizerany You are right! I gave `tier switch` a spin and really love the idea. Prefer it over force-push for testing. Some questions:

1. Ability to delete/flush test accounts instead of doing it through the UI. Is this on the horizon?
2. List of test accounts to switch to (like `git branch`). Not thought through this but I might see a situation where one is experimenting with multiple variations of the Model and would want to switch between them to see which works best?
3. `tier push <pricing.json>` output currently provides links to main account instead of the switched account. I guess this needs to be changed too?

As far as grandfather accounts is concerned, I feel force-pushing features would still be valuable. Since the [PriceOps Metering document](https://priceops.org/3-metering) mentions that:

> Thus, anything that can potentially be a restricted or monetized feature is tracked in the metering system, even if the current price (as defined in the [model](https://priceops.org/1-model)) is 0.

New features (or even feature changes), in my opinion, should be retroactively added/modified to grandfathered accounts even if price for that feature is set to 0 for such accounts. I am guessing feature flags would require feature to be in the plan for it to validate if the user is allowed to access said feature or not. If the plan is made purely immutable then those grandfathered accounts will have to resubscribe to be able to use new features. Maybe this can be an exception to Model being purely immutable?

> they would instead be seen to tier as having "fragments" and would not be considered on any plan (assuming they were not subscribed to two plans at once), and this should not be allowed by Tier in live-mode, so it could be cause confusion amongst users as to why behaviors around subscriptions and limits, etc suddenly changed for customers that have not upgraded or downgraded in a way one might think they should be.

I did not understand what "fragments" are in this context. Can you please explain? Are these features free-floating and not tied to a plan specifically? Is this some way to ensure Models remain immutable but features are still applied for grandfathered accounts?

**Comment by bmizerany** [comment]
> @bmizerany You are right! I gave `tier switch` a spin and really love the idea. Prefer it over force-push for testing. Some questions:

I'm so happy to hear that!

> 
> 1. Ability to delete/flush test accounts instead of doing it through the UI. Is this on the horizon?

This is on the horizon. The plan is to do this in the background after a `tier switch` exits, and to only garbage collect accounts older than N days. My current thinking is somewhere between 10-20 days. This could be configurable of course and also come with a way to force a garbage collection for N days. Maybe something like `tier switch --gc 10d`?

I've created an issue to track here: https://github.com/tierrun/tier/issues/164

> 2. List of test accounts to switch to (like `git branch`). Not thought through this but I might see a situation where one is experimenting with multiple variations of the Model and would want to switch between them to see which works best?

Yes. I want this too. I'm playing with some ideas. I've opened an issue for tracking: https://github.com/tierrun/tier/issues/165

> 3. `tier push <pricing.json>` output currently provides links to main account instead of the switched account. I guess this needs to be changed too?

Great catch. I've created an issue to track here: https://github.com/tierrun/tier/issues/166



> 
> As far as grandfather accounts is concerned, I feel force-pushing features would still be valuable. Since the [PriceOps Metering document](https://priceops.org/3-metering) mentions that:
> 
> > Thus, anything that can potentially be a restricted or monetized feature is tracked in the metering system, even if the current price (as defined in the [model](https://priceops.org/1-model)) is 0.
> 
> New features (or even feature changes), in my opinion, should be retroactively added/modified to grandfathered accounts even if price for that feature is set to 0 for such accounts. I am guessing feature flags would require feature to be in the plan for it to validate if the user is allowed to access said feature or not. If the plan is made purely immutable then those grandfathered accounts will have to resubscribe to be able to use new features. Maybe this can be an exception to Model being purely immutable?
> 
> > they would instead be seen to tier as having "fragments" and would not be considered on any plan (assuming they were not subscribed to two plans at once), and this should not be allowed by Tier in live-mode, so it could be cause confusion amongst users as to why behaviors around subscriptions and limits, etc suddenly changed for customers that have not upgraded or downgraded in a way one might think they should be.
> 
> I did not understand what "fragments" are in this context. Can you please explain? Are these features free-floating and not tied to a plan specifically?

Tier calculates all of the plans an org is currently subscribed to by testing if all of its companion features, in the same plan, are present the org's current subscription. If not, it is considered a fragment.

A demonstration of how fragments happen (by design):

```
tier % tier ls
PLAN         FEATURE                 MODE  AGG  BASE
plan:free@0  feature:convert:temp               1
plan:pro@0   feature:convert:temp               0
plan:pro@0   feature:convert:volume             1
plan:pro@0   feature:convert:weight             1
plan:pro@1   feature:convert:volume             1
plan:pro@1   feature:convert:weight             1
tier % tier subscribe org:fragments plan:free@0 feature:convert:weight@plan:pro@0
tier % curl 'http://localhost:8080/v1/phase?org=org:fragments'
{
        "effective": "2022-11-18T00:29:50Z",
        "features": [
                "feature:convert:temp@plan:free@0",
                "feature:convert:weight@plan:pro@0"
        ],
        "plans": [
                "plan:free@0"
        ],
        "fragments": [
                "feature:convert:weight@plan:pro@0"
        ]
}
tier % tier limits org:fragments
FEATURE                 LIMIT  USED
feature:convert:temp    ∞      1
feature:convert:weight  ∞      1
```

Fragments are features in a subscription that are not accompanied by all of the other features in the same plan. For example, you may want to subscribe an org to a free plan, but give them a small taste of the pro plan. 

Back to force-push. If we allow force-pushes, then it means fragments can happen inadvertently. Please see how that happens today without enforcing immutability:

Building on the state from the previous demo, I'll "force push" (because tier does not enforce immutability at the moment) a new feature to "plan:free@0", and then check which plans and fragments the `org:fragments` is on:

```
tier % cue export p.cue | tier push -
ok      plan:pro@0      feature:convert:temp    https://dashboard.stripe.com/test/products      [feature already exists]
ok      plan:free@0     feature:convert:temp    https://dashboard.stripe.com/test/products      [feature already exists]
ok      plan:free@0     feature:convert:blarbs  https://dashboard.stripe.com/test/products      [created]
tier: feature already exists
tier % curl 'http://localhost:8080/v1/phase?org=org:fragments'
{
        "effective": "2022-11-18T00:29:50Z",
        "features": [
                "feature:convert:temp@plan:free@0",
                "feature:convert:weight@plan:pro@0"
        ],
        "fragments": [
                "feature:convert:temp@plan:free@0",
                "feature:convert:weight@plan:pro@0"
        ]
}

```

As you can see, the org morphed from being on a plan, to be on some plan of its own, which is no real plan at all. This might be a desired state to put a customer in, but not one we want customers to accidentally transition to, without warning, because this makes determining which plan they _were_ on difficult, if not impossible.

I hope the demonstrations help clear things up around what happens if immutability is not enforced, and what fragments are, and also show off a really powerful feature "fragments" that is undocumented... for now. :)

I'd like to add the enforcement of immutability, without force-push as a first-pass, and get a feel for what life is like with it, and also with using `switch` and version-bumping as _workarounds_ to force pushing.

**Comment by bmizerany** [comment]
@shripadk I'm sorry, I left out a reply in my previous post to a question of yours:

> Is this some way to ensure Models remain immutable but features are still applied for grandfathered accounts?

Yes, but it should require an intermediate migration step, one we can make very easy with an additional tool in the CLI.

The reason for requiring the intermediate migration step is that there is no one-size-fits-all migration. Different companies have different ways they want to handle grandfathering, if at all. It could be done by cohort, all-at-once, regional, etc.

The current default behavior is the safest we feel, which happens to be the default behavior in Stripe, and there are no plans to change that default. However, having some nice tools for migrating customers if new plans go live should make it a breeze to handle.

The command might look something like this if one wants to migrate all customers on a plan to a new plan:

```
; tier migrate plan:pro@1 plan:pro@3
```

This command would have a few different forms for common migration needs.

**Comment by bmizerany** [comment]
@shripadk, @jevon I landed a PR that runs 'pre-flight' checks to ensure immutability of plans. It uses a sentinel product in Stripe to determine if anything has been pushed for a plan already.

If no sentinel plans exist for existing plans, it is still possible to push new features to plans that existed before the sentinel products are written to Stripe. To play with this new feature, and add sentinels for exiting products, safely, and  pre release, you can install from source and run:

```
; tier pull | tier push -
```

I recommended running the above at least twice. The first will show, unsurprisingly, that all of the features already exist, as was seen before, because the sentinel products just now made it into stripe, but subsequent runs of it should show `[plan already exists]` which means the sentinels made it in and Tier is disallowing anything that smells like an update to the plan. It is safe to run because it only attempts to push objects that already exist, along with the the new sentinel products.
