### ISSUE TITLE
FR: return something from successful POSTs to sidecar

### ISSUE THREAD

**Issue by isaacs** [tierrun/tier#125]
### What are you trying to do?

Trying to verify that a write operation to the sidecar was successful.  Right now, errors return a consistent data shape, which is very good, but successful POSTs just return an empty response body.  This makes it somewhat inconvenient, since I can't just `await res.json()`, as that'll fail when the POST succeeded.

### How should we solve this?

It would be good if every POST request to the sidecar returned at minimum a `{status, ok: true, ...}` object, which could include additional metadata as appropriate.  (For example, `/v1/subscribe` could return the user's CustomerID, current phase, idk, something you're likely to fetch anyway, soon after writing.  `/v1/report` could return the updated usage, so you don't have to hit `/v1/limits` again, etc.)

### What is the impact of not solving this?

Have to do a little more work to only parse the body if it's an error, and occasionally need to make a GET shortly after a POST.  (Not really a huge deal, but mildly annoying.)

**Comment by bmizerany** [comment]
> ### What are you trying to do?
> Trying to verify that a write operation to the sidecar was successful. Right now, errors return a consistent data shape, which is very good, but successfuTs just return an empty response body. This makes it somewhat incovenient, since I can't just `await res.json()`, as that'll fail when the POST succeeded.

It returns a 200 status. I can see an argument for something other than an empty string, such as `{}`, but stuttering the status or anything that could otherwise be interpreted from the status code seems wasteful. I say this as the person that copied Stripe's way of doing it in our errors and never once ever looked at the body's `status` field because I've already looked at the status code. :) 

Please see the Go SDK that uses a helper to switch on the status code and parse the appropriate type based on it. All exported function share use of that so it's done in one place and is used each time a new method is added.

> 
> ### How should we solve this?
> It would be good if every POST request to the sidecar returned at minimum a `{status, ok: true, ...}` object, which could include additional metadata as appropriate. (For example, `/v1/subscribe` could return the user's CustomerID, current phase, idk, something you're likely to fetch anyway, soon after writing. `/v1/report` could return the updated usage, so you don't have to hit `/v1/limits` again, etc.)

Reporting usage doesn't necessitate needing to see the limits after.  Limits are intended to be looked up before reporting usage because why allow usage if they are over their limits? I don't see the case for adding and supporting such a response currently.

As for customer IDs, those are intentionally hidden and to get them requires a special API endpoint purely for Stripe-specific things like payment links which is a rare event and not something always done upon subscribing. It's pretty common to start someone on a free plan without requiring payment information. I'd like to hold off on adding a second way to acquire a customerID until we have strong evidence it's worth officially supporting in the API.

I'd like to have extremely compelling reasons to commit to fields returned in response objects. Again, I do think it's best to return `{}` at the minimum so we have the option to add fields later with major API version bumps.


> 
> ### What is the impact of not solving this?
> Have to do a little more work to only parse the body if it's an error, and occasionally need to make a GET shortly after a POST. (Not really a huge deal, but mildly annoying.)
> 
> ### Anything else?
> _No response_

**Comment by bmizerany** [comment]
Fixed in #140
