### ISSUE TITLE
Subscribing through checkout doesn't cancel previous subscriptions

### ISSUE THREAD

**Issue by isaacs** [tierrun/tier#224]
### What is the issue?

Subscribing a customer via checkout does not cancel existing plans, as it would when going through the `/v1/subscribe` API.

### Steps to reproduce

Subscribe a customer via checkout:

```js
const { url } = await tier.checkout(org, { successUrl: 'https://whatever', features: ['plan:free@1'] })
return redirect(url)
```

Get the redirect, click the buttons, return to the app.

Then, pick a new plan, and do the same thing.

Result:

<img width="540" alt="Screenshot 2023-01-26 at 10 49 16" src="https://user-images.githubusercontent.com/9287/214923478-6c25cc62-3ef4-48c4-9d06-9a48810dac8d.png">

Expect to see only the most recent plan chosen.

### OS

macOS

### OS version

Darwin moxy.lan 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64

### Tier version

0.7.1   tier commit: d058cdac601f0764bd54f856de316ad068b5fcd4   go version: go1.20rc2

**Comment by bmizerany** [comment]
It seems the real goal is to upgrade/downgrade without canceling anything, so I propose one of these (and below a workaround that should work today):

1. Return an error if checkout is requested for an org that already has a subscription. This leaves what to do next to clients, but it should be safe to say most will reroute the subscription update right back to `/v1/subscribe` sans the checkout option, and so as an alternate approach to returning an error:
2. Auto upgrade/downgrade the active subscription if one already exists, skipping the Checkout dance and responding without a Checkout link as a sign it was "handled.", or:
3. Go with option 2, and add that the URL will be the supplied success_url if an update happened successfully so that clients can redirect to whatever URL comes back from the request, making it transparent what is happening to clients, they can just blindly redirect and get the same behavior they would get from checkout. 

The above are more favorable to the alternatives below:

- "overly optimistic cancelation of current schedule to accept the soon-to-be authorized one": This isn't great because if the customer cancels out of checkout, they are no longer subscribed to anything, among other undesirable side effects.
- waiting to cancel on getting to `success_url`: Like relying on webhooks, this isn't ideal either. Things can go wrong, and the client may never receive a callback, leaving the customer with multiple subscriptions.

I personally lean to option 3.

As a workaround today, clients can check if there is an active phase using the `/v1/phase` endpoint and either using checkout or simply upgrading or downgrading the current schedule.

This issue will remain open until we either implement the error response or decide to fix it with documentation.

**Comment by bmizerany** [comment]
A workaround exists: Check for phases before calling checkout in subscription mode. Closing. In the future we may revisit with a new approach to checkout+billing portal.
