### ISSUE TITLE
FR: Browser SDK / Client

### ISSUE THREAD

**Issue by itsezc** [tierrun/tier#227]
### What are you trying to do?

Building CSR / SSG apps with Tier would be amazing, as I plan to develop one, currently this is not possible as the Node SDK is limited to server environments and not the browser / client.

### How should we solve this?

Ideally, make the existing JS SDK work on the browser or develop one that can

### What is the impact of not solving this?

Unable to build CSR / SSG apps with Tier

**Comment by isaacs** [comment]
Since tier works with sensitive data (like, for example, your stripe key!), it'd be impossible to have a _full_ tier client that works safely in the browser.  I'm not sure how it'd be something we could do without a managed service.  (Since you also can't run the compiled go sidecar in the browser, either.)

Once we do have such a service (which should be fairly soon!), then there are certainly some angles we could explore. We'd still want to use some kind of time-limited and/or customer-scoped keys for security reasons, so there'd have to be _some_ server-side logic.  (Of course, at that point, it could be small enough to fit comfortably an AWS Lambda or some other cloud function that you hit via client-side `fetch()`.)

**Comment by isaacs** [comment]
Anything we do in this space really needs to be thought through _very_ carefully, because the last thing you'd want is for full access to your billing data to be shared with any random user that hits your website.

**Comment by isaacs** [comment]
Hey, just circling back on this with an update.  (Closing, not because it's a rejected idea, but because we're tracking it elsewhere, and I don't want this issue to be left hanging open indicating that it's not being done.  But if you have other questions or suggestions, feel free to keep discussing here.)

- The [Tier Node SDK](https://github.com/tierrun/node-sdk) is actually also a "JavaScript SDK", though of course the automatic creation of a sidecar, process.env detection, etc., only works in node environments.  But you _can_ pull in the `client.js` file and it'll be able to talk to an API server that sends the appropriate CORS headers.
- The Tier Cloud server at https://api.tier.run has CORS support, but currently is only allowed from the host https://model.tier.run (we're using this to support pushing a model to Stripe from the browser).  This isn't something that could be put to general use yet, of course, because of the CORS host restriction, but we are dogfooding the pattern, for what it's worth.
- We have plans to add support for a "publishable key" and other common service niceties as we build out the hosted service, which will allow you to do certain non-privileged things.  As I mentioned previously, this has to be done very carefully for obvious security reasons, but for example, it would be nice to be able to fetch your model to display a pricing page, check in the browser if a user has access to a certain feature when generating page UI, etc.  Feature usage reporting, subscription, and model changes would all require privileged access, and have to be done server-side (or client-side, but with a Stripe oauth; ie, not in your _customer's_ browser, but in yours).
- As part of all this, a "React SDK" is sort of growing organically as we build out features that the model builder needs.  I personally think it's best to develop these sorts of things in this way, letting the patterns emerge from usage and real needs rather than being forced.  Our current vision for what that SDK will include is probably limited to:
  - a suite of template tags that can fetch your model and be assembled usefully in creating a pricing page.  (These will be unstyled components, along with some default styles that you can choose to apply, or you can use Tailwind or CSS or whatever you like on them.)
  - A context provider that loads a client and can fetch data that it has access to.
  - A `<TierCan feature="feature:...">` component that will show or hide its contents based on whether the org has access to the given feature.  Of course, this won't be a _security_ restriction, since the markup will still be there in the page data, but it won't be mounted, which can be convenient to at least avoid showing something that will fail when your customer tries to use it.  (And a corresponding `<TierCannot>` component to show "Upgrade your account!" or whatever, if they *don't* have access to it.)
  - Possibly some helper components for whatever other features we enable with a publishable key.  One that comes to mind that would be really handy is a way to get a checkout subscribe link, so you can do `<TierCheckoutLink plan="plan:...">Subscribe Now!</TierCheckoutLink>` etc.

Of course, all of this is very early stages still, and may completely change as we learn more, so take it with a grain of salt.  But if there are parts that are interesting to you, definitely [come to our slack channel](https://join.slack.com/t/tier-community/shared_invite/zt-1blotqjb9-wvkYMo8QkhaEWziprdjnIA) and let us know your thoughts :)
