### ISSUE TITLE
`tier pull` doesn't show plans that do not have features

### ISSUE THREAD

**Issue by isaacs** [tierrun/tier#36]
Not sure how relevant this is, but it certainly is weird.  Discovered making minimal repro case for #35, it turns out `tier pull` doesn't even show plans if there's no Price data in Stripe.

```
$ go run tier.run/cmd/tier@oauth pull 
{
     "plans": {
          "plan:foo_bar@baz": {
               "features": {...}
          },
          "plan:free@1": {
               "features": {...}
          },
          "plan:free@420": {
               "features": {...}
          },
          "plan:pro@1": {
               "features": {...}
          },
          "plan:pro@420": {
               "features": {...}
          }
    }
}
```

Note that `plan:1_2@3` is missing, even though the Product was created in stripe.

<img width="358" alt="Screen Shot 2022-09-06 at 17 53 36" src="https://user-images.githubusercontent.com/9287/188765097-0fe683d7-00de-487d-a711-ffc162ea45aa.png">

**Comment by bmizerany** [comment]
Should we allow a plan without features? Is it useful to have a plan without features? Once made, it can never have features. Maybe the right thing to do here is disallow them when we address #16 ?

**Comment by isaacs** [comment]
A "plan without features" could be useful if you want to use it as a starter plan with no access to anything paid, or something.  But yes, it's sort of useless.

I think the reasonable approach is _either_:

- Error and refuse to `tier push` if a plan lacks features.
- Pull price-less products as a feature-less plan in `tier pull`.

**Comment by isaacs** [comment]
Not a terribly huge consideration, but I do have a featureless docs as an example in the step-by-step explanation of pricing.json components.  Ie, this is a plan, now add features to it, etc.  If that's invalid, I'll have to make a note of that, or maybe highlight that tier won't let you push it in that state.

**Comment by bmizerany** [comment]
> Pull price-less products as a feature-less plan in tier pull

The way it works currently is to pull all prices and "expand" the products and build the model from there. This means products without prices are omitted.

Inverting this design will mean more API calls to stripe because you can't "expand" prices in products, so we would need to fetch all products along with all prices outer join, which is doable, but I also believe it is avoidable if we consider adding a surrogate feature `feature:_` with no price to any plan without features?

**Comment by bmizerany** [comment]
Another thought. We could have a `plan:cancel@0` which is a special plan _created_ by Tier that has no features, and it is the only plan allowed to have zero features. All other vendor-defined features must have at least one feature.

When a vendor appends a phase to a schedule that is `plan:cancel@0` then Tier will explicitly cancel the schedule in Stripe (which is a specific thing in Stripe vs our pervious way of reasoning about it with the use of features and limits).

**Comment by bmizerany** [comment]
Also, in Stripe Billing, Products are useless. With schedules,  you can mix an match prices from various products into a single phase, so they have no real value. We only create them because we have to in order to create a price in Stripe.

I've been fantasizing about moving to a 1:1 mapping of product to price in Stripe and using only Metadata to "group" the features into "plans".

**Comment by isaacs** [comment]
decision: plans must have features

- [ ] update docs to say this
- [ ] update validation to enforce this

**Comment by bmizerany** [comment]
Plans are now required to have features: https://github.com/tierrun/tier/pull/43

Please close this ticket at will.

**Comment by bmizerany** [comment]
@isaacs Is it safe to close this? If so do you mind doing so?

**Comment by bmizerany** [comment]
Closing. Please reopen if you believe it should not be closed.
