### ISSUE TITLE
`-l` not always an alias for `--live`

### ISSUE THREAD

**Issue by isaacs** [tierrun/tier#97]
### What is the issue?

```
$ tier -l serve
flag provided but not defined: -l
```

And yet:

```
$ tier --live serve
listening on [::]:8080
```

### Steps to reproduce

```
$ tier -l serve
flag provided but not defined: -l
```

**Comment by bmizerany** [comment]
This works as intended. Are you proposing we have a short version of the flag? It's a pretty serious flag to set and providing a way to deemphasize that seems dangerous.

If you're spending a lot of time on the cli and needing a live key and want to fly by the seat of your pants, one can set STRIPE_API_KEY which takes precedence over the config.json.

Now that I bring that up, tier should exit with an error if the STRIPE_API_KEY is set to a live key, and `--live` is not set (this include `tier serve`)

It might even be a good idea to require the account name as the value for `--live` like `--live=blake.io` so that all of the `ctrl-r` in the shell have that prefix to the command to make you think twice about hitting enter.

Tier should be, but also very much feel, safe to use. It shouldn't feel like a mousing cat you keep in the house that also likes to claw your face if you look at it wrong.

**Comment by bmizerany** [comment]
I've added an issue to work on the above https://github.com/tierrun/tier/issues/99

**Comment by bmizerany** [comment]
This discussion can be moved to #99.
